=== Oravlalesco/l2dn-server/L2Dn/L2Dn.GameServer/DataPack/xsd/DailyMission.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list" type="listType" />
	<xs:complexType name="paramType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="handlerType">
		<xs:sequence>
			<xs:element type="paramType" name="param" maxOccurs="unbounded" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="itemType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:int" name="id" use="required" />
				<xs:attribute type="xs:int" name="count" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="itemsType">
		<xs:sequence>
			<xs:element type="itemType" name="item" maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="rewardType">
		<xs:sequence>
			<xs:element type="xs:short" name="classId" maxOccurs="unbounded" minOccurs="0" />
			<xs:element type="handlerType" name="handler" minOccurs="1" maxOccurs="1" />
			<xs:element type="itemsType" name="items" />
		</xs:sequence>
		<xs:attribute type="xs:short" name="id" use="required" />
		<xs:attribute type="xs:short" name="reward_id" />
		<xs:attribute type="xs:string" name="name" />
		<xs:attribute type="xs:int" name="requiredCompletion" use="required" />
		<xs:attribute type="xs:boolean" name="dailyReset" />
		<xs:attribute type="xs:boolean" name="isOneTime" />
		<xs:attribute type="xs:boolean" name="isMainClassOnly" />
		<xs:attribute type="xs:boolean" name="isDualClassOnly" />
		<xs:attribute type="xs:boolean" name="isDisplayedWhenNotAvailable" />
		<xs:attribute type="xs:string" name="duration" />
	</xs:complexType>
	<xs:complexType name="listType">
		<xs:sequence>
			<xs:element type="rewardType" name="reward" maxOccurs="unbounded" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Oravlalesco/l2dn-server/L2Dn/L2Dn.GameServer/DataPack/DailyMission.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/DailyMission.xsd">
	<reward id="1001" reward_id="101" name="Daily Hunting I (Lv. 1-20)" requiredCompletion="30" isOneTime="false">
		<!-- Daily quest. A reward is given for killing any 30 monsters. Monsters below character for 5 or more levels are not counted. -->
		<handler name="monster">
			<param name="minLevel">1</param>
			<param name="maxLevel">20</param>
		</handler>
		<items>
			<item id="49674" count="1" />
			<item id="71438" count="5" />
		</items>
	</reward>
	<reward id="1002" reward_id="102" name="Daily Hunting I (Lv. 21-40)" requiredCompletion="30" isOneTime="false">
		<!-- Daily quest. A reward is given for killing any 30 monsters. Monsters below character for 5 or more levels are not counted. -->
		<handler name="monster">
			<param name="minLevel">21</param>
			<param name="maxLevel">40</param>
		</handler>
		<items>
			<item id="49674" count="1" />
			<item id="49779" count="1" />
			<item id="49595" count="1" />
			<item id="71438" count="5" />
		</items>
	</reward>
	<reward id="1003" reward_id="103" name="Daily Hunting I (Lv. 41-50)" requiredCompletion="40" isOneTime="false">
		<!-- Daily quest. A reward is given for killing any 40 monsters. Monsters below character for 5 or more levels are not counted. -->
		<handler name="monster">
			<param name="minLevel">41</param>
			<param name="maxLevel">50</param>
		</handler>
		<items>
			<item id="49674" count="1" />
			<item id="71438" count="5" />
		</items>
	</reward>
	<reward id="1004" reward_id="104" name="Daily Hunting I (Lv. 51-60)" requiredCompletion="50" isOneTime="false">
		<!-- Daily quest. A reward is given for killing any 50 monsters. Monsters below character for 5 or more levels are not counted. -->
		<handler name="monster">
			<param name="minLevel">51</param>
			<param name="maxLevel">60</param>
		</handler>
		<items>
			<item id="49674" count="1" />
			<item id="71438" count="5" />
		</items>
	</reward>
	<reward id="1005" reward_id="105" name="Daily Hunting I (Lv. 61-70)" requiredCompletion="60" isOneTime="false">
		<!-- Daily quest. A reward is given for killing any 60 monsters. Monsters below character for 5 or more levels are not counted. -->
		<handler name="monster">
			<param name="minLevel">61</param>
			<param name="maxLevel">70</param>
		</handler>
		<items>
			<item id="49674" count="1" />
			<item id="71438" count="5" />
		</items>
	</reward>
	<reward id="1006" reward_id="106" name="Daily Hunting I (Lv. 71-75)" requiredCompletion="80" isOneTime="false">
		<!-- Daily quest. A reward is given for killing any 80 monsters. Monsters below character for 5 or more levels are not counted. -->
		<handler name="monster">
			<param name="minLevel">71</param>
			<param name="maxLevel">75</param>
		</handler>
		<items>
			<item id="49674" count="1" />
			<item id="71438" count="5" />
		</items>
	</reward>
	<reward id="1007" reward_id="107" name="Daily Hunting I (Lv. 76+)" requiredCompletion="100" isOneTime="false">
		<!-- Daily quest. A reward is given for killing any 100 monsters. Monsters below character for 5 or more levels are not counted. -->
		<handler name="monster">
			<param name="minLevel">76</param>
			<param name="maxLevel">99</param>
		</handler>
		<items>
			<item id="49674" count="1" />
			<item id="71438" count="5" />
		</items>
	</reward>
	<!-- TODO: Weekly fishing handler
	<reward id="1015" reward_id="115" name="Fishing" requiredCompletion="100" isOneTime="false">
		Weekly quest. A reward is given for 100 successful catches.
		<handler name="fishing">
			<param name="minLevel">76</param>
			<param name="maxLevel">99</param>
		</handler>
		<items>
			<item id="90139" count="360" />
		</items>
	</reward>
	-->
	<reward id="1017" reward_id="117" name="In-game Weekend" requiredCompletion="1" isOneTime="false" duration="WEEKEND">
		<!-- Weekly quest. A reward is given for playing the game on Saturday or Sunday. -->
		<handler name="loginweekend" />
		<items>
			<item id="91781" count="1" />
		</items>
	</reward>
	<reward id="1021" reward_id="121" name="Siege Participation" requiredCompletion="1" isOneTime="false">
		<!-- Weekly quest. A reward is given for participating in 1 siege (the character must be on the battlefield when the siege starts). Required level: 40. -->
		<handler name="siege">
			<param name="minLevel">40</param>
			<param name="maxLevel">99</param>
		</handler>
		<items>
			<item id="70000" count="1" />
		</items>
	</reward>
	<reward id="1023" reward_id="501" name="Joining a Clan" requiredCompletion="1">
		<!-- One-time quest. A reward is given when joining a clan for the first time. -->
		<handler name="joinclan" />
		<items>
			<item id="29978" count="1" />
		</items>
	</reward>
	<reward id="1095" reward_id="803" name="Clan Raid Attack" requiredCompletion="1" isOneTime="false">
		<!-- Weekly quest. A reward is given for defeating 1 enemy in the Clan Arena. Required level: 40. -->
		<handler name="monster">
			<param name="ids">25794,25795,25796,25797,25798,25799,25800,25801,25802,25803,25804,25805,25806,25807,25808,25809,25810,25811,25812,25813</param>
			<param name="minLevel">40</param>
			<param name="maxLevel">99</param>
		</handler>
		<items>
			<item id="91781" count="3" />
		</items>
	</reward>
	<reward id="1096" reward_id="804" name="Clan Raid Suppression" requiredCompletion="20" isOneTime="true" dailyReset="false">
		<!-- One-time quest. A reward is given for defeating 20 enemies in the Clan Arena. Required level: 40. -->
		<handler name="monster">
			<param name="ids">25794,25795,25796,25797,25798,25799,25800,25801,25802,25803,25804,25805,25806,25807,25808,25809,25810,25811,25812,25813</param>
			<param name="minLevel">40</param>
			<param name="maxLevel">99</param>
		</handler>
		<items>
			<item id="91781" count="10" />
		</items>
	</reward>
	<!-- FIXME: Add ids.
	<reward id="1102" reward_id="806" name="Exploring the Alligator Island (Lv. 35-50)" requiredCompletion="100" isOneTime="false">
		Daily quest. A reward is given for killing 100 Noses on the Alligator Island.
		<handler name="monster">
			<param name="minLevel">35</param>
			<param name="maxLevel">50</param>
		</handler>
		<items>
			<item id="49781" count="3" />
		</items>
	</reward>
	-->
	<reward id="1103" reward_id="807" name="Exploring the Forest of Mirrors (Lv. 45-60)" requiredCompletion="30" isOneTime="false">
		<!-- Daily quest. A reward is given for killing 30 Harit Earth Guardians in the Forest of Mirrors. -->
		<handler name="monster">
			<param name="targetMode">NPC_IDS</param>
			<param name="ids">20636,20637,20638,20639,20640,20641,20642,20643,20644,20645</param>
			<param name="minLevel">45</param>
			<param name="maxLevel">60</param>
		</handler>
		<items>
			<item id="49781" count="7" />
		</items>
	</reward>
	<reward id="1104" reward_id="808" name="Exploring the Seal of Shilen (Lv. 55-70)" requiredCompletion="30" isOneTime="false">
		<!-- Daily quest. A reward is given for killing 30 Palibati Earth Guardians near the Seal of Shilen. -->
		<handler name="monster">
			<param name="ids">20673</param>
			<param name="minLevel">55</param>
			<param name="maxLevel">70</param>
		</handler>
		<items>
			<item id="49781" count="9" />
		</items>
	</reward>
	<reward id="1105" reward_id="809" name="Exploring the Forsaken Plains (Lv. 65-75)" requiredCompletion="30" isOneTime="false">
		<!-- Daily quest. A reward is given for killing 30 Sharp Talon Tigers in the Forsaken Plains. -->
		<handler name="monster">
			<param name="ids">21021</param>
			<param name="minLevel">65</param>
			<param name="maxLevel">75</param>
		</handler>
		<items>
			<item id="49781" count="11" />
		</items>
	</reward>
	<reward id="1106" reward_id="810" name="Exploring the Hot Springs (Lv. 76+)" requiredCompletion="100" isOneTime="false">
		<!-- Daily quest. A reward is given for killing 100 monsters in the Hot Springs: Hot Springs Yeti, Hot Springs Buffalo, Hot Springs Grendel. -->
		<handler name="monster">
			<param name="ids">21839,21834,21842</param>
			<param name="minLevel">76</param>
			<param name="maxLevel">99</param>
		</handler>
		<items>
			<item id="90917" count="3" />
		</items>
	</reward>
	<!-- TODO: spiritevolve handler
	<reward id="1112" reward_id="508" name="Fire Spirit Lv. 3" requiredCompletion="3">
		One-time quest. A reward is given when evolving the Fire Spirit up to Lv. 3.
		<handler name="spiritevolve">
			<param name="element">FIRE</param>
		</handler>
		<items>
			<item id="91185" count="30" />
		</items>
	</reward>
	<reward id="1113" reward_id="509" name="Water Spirit Lv. 3" requiredCompletion="3">
		One-time quest. A reward is given when evolving the Water Spirit up to Lv. 3.
		<handler name="spiritevolve">
			<param name="element">WATER</param>
		</handler>
		<items>
			<item id="91185" count="30" />
		</items>
	</reward>
	<reward id="1114" reward_id="510" name="Wind Spirit Lv. 3" requiredCompletion="3">
		One-time quest. A reward is given when evolving the Wind Spirit up to Lv. 3.
		<handler name="spiritevolve">
			<param name="element">WIND</param>
		</handler>
		<items>
			<item id="91185" count="30" />
		</items>
	</reward>
	<reward id="1115" reward_id="511" name="Earth Spirit Lv. 3" requiredCompletion="3">
		<handler name="spiritevolve">
			<param name="element">EARTH</param>
		</handler>
		One-time quest. A reward is given when evolving the Earth Spirit up to Lv. 3.
		<items>
			<item id="91185" count="30" />
		</items>
	</reward>
	-->
	<!-- TODO: Weekly monster handler
	<reward id="1116" reward_id="118" name="Attribute monsters hunting" requiredCompletion="1800">
		Receive it once a week for Attribute monster hunting.
		<handler name="monster">
